bytecast.storage.bucket=bytecast
quarkus.minio.host=http://localhost:9000
quarkus.minio.access-key=minioaccess
quarkus.minio.secret-key=miniosecret
quarkus.minio.secure=false

quarkus.cache.caffeine."video-metadata".expire-after-write=1h
quarkus.cache.caffeine."video-metadata-master.m3u8".expire-after-write=1h